# Generated by Django 6.1.1 on 2026-09-21 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Excavator 4"', max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='tracker.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(help_text='ESP32 chip ID', max_length=100, unique=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='tracker.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='FaultEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spn', models.IntegerField(verbose_name='SPN')),
                ('fmi', models.IntegerField(verbose_name='FMI')),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_events', to='tracker.equipment')),
            ],
            options={
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='HourReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('recorded_at', models.DateTimeField(help_text="Device's own clock, not server receipt time")),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_readings', to='tracker.equipment')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField()),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('parts_used', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hours_at_service', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='tracker.equipment')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='OilSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField()),
                ('hours_at_sample', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('wear_metals', models.JSONField(blank=True, default=dict, help_text='e.g. iron/copper/silicon in ppm')),
                ('viscosity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('contamination_flags', models.CharField(blank=True, max_length=300)),
                ('lab_recommendation', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_samples', to='tracker.equipment')),
            ],
            options={
                'ordering': ['-sampled_at'],
            },
        ),
    ]
