# Generated by Django 6.1.1 on 2026-09-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_equipment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='e.g. "Oil and filter change"', max_length=200)),
                ('interval_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Recurs every N engine hours, if hour-based', max_digits=10, null=True)),
                ('interval_days', models.IntegerField(blank=True, help_text='Recurs every N calendar days, if time-based instead', null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='tracker.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='tracker.maintenanceschedule'),
        ),
        migrations.CreateModel(
            name='TelemetryPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(help_text="Device's own clock, not server receipt time")),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kph', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pm25', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='PM2.5 (µg/m³)')),
                ('vibration_magnitude', models.DecimalField(blank=True, decimal_places=2, help_text='Relative intensity, not calibrated g-force', max_digits=6, null=True)),
                ('is_impact_event', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_pings', to='tracker.equipment')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
