# Generated by Django 6.1.1 on 2026-09-21 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('equipment_down', models.BooleanField(default=True, help_text='Was the machine out of service while this was open?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tracker.equipment')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='tracker.issue')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='tracker.maintenanceschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
