# Generated by Django 6.1.1 on 2026-09-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_device_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='site_name',
            field=models.CharField(blank=True, help_text='Job site this unit is currently deployed to, e.g. "Site 12 – Downtown Interchange"', max_length=200),
        ),
    ]
