# Generated by Django 6.1.1 on 2026-09-22 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_equipment_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='labor_cost',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='parts_cost',
        ),
        migrations.CreateModel(
            name='WorkOrderLaborLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.CharField(max_length=200)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, default=120, help_text='$/hour', max_digits=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_lines', to='tracker.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_lines', to='tracker.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
