# Generated by Django 6.1.1 on 2026-09-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_workorder_labor_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='site_name',
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Site 12 – Downtown Interchange"', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='tracker.customer')),
            ],
            options={
                'ordering': ['customer__name', 'name'],
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Job site this unit is currently deployed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='tracker.site'),
        ),
    ]
