# Generated by Django 6.1.1 on 2026-09-24 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_backfill_user_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by', models.CharField(max_length=200)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('hours_at_inspection', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('responses', models.JSONField(default=dict, help_text='{"item_key": "ok"|"issue"|"na"}')),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tracker.equipment')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
