# Generated by Django 6.1.1 on 2026-09-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_userprofile_api_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Default cost used to prefill a work order part line', max_digits=10)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=2, help_text='Flag as low stock at or below this quantity; leave blank to never flag', max_digits=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='{"item_key": "comment text"} -- only items worth a note need an entry'),
        ),
        migrations.AddField(
            model_name='photo',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tracker.inspection'),
        ),
        migrations.AddField(
            model_name='photo',
            name='item_key',
            field=models.CharField(blank=True, help_text='For an inspection photo: which checklist item ("engine_oil") or walkaround side ("side_front"/"side_back"/"side_left"/"side_right") this documents.', max_length=50),
        ),
        migrations.AddField(
            model_name='workorderpartline',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Linked inventory item, if this part is stocked -- leave blank for a one-off part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_lines', to='tracker.part'),
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracker.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
