# Generated by Django 6.1.1 on 2026-09-25 22:35

from django.db import migrations, models


def reassign_supervisors_to_admin(apps, schema_editor):
    """Supervisor is being dropped from the role taxonomy (Operator/Technician/Admin
    replaces Technician/Supervisor/Admin). A supervisor previously had Manage+Reports
    access -- closer to Admin than to the new, narrower Technician -- so existing
    supervisor accounts get bumped to Admin rather than silently losing access.
    Reassign manually via Manage Users if that's not the right call for a given account."""
    UserProfile = apps.get_model("tracker", "UserProfile")
    UserProfile.objects.filter(role="supervisor").update(role="admin")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_part_inspection_comments_photo_inspection_and_more'),
    ]

    operations = [
        migrations.RunPython(reassign_supervisors_to_admin, noop),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('technician', 'Technician'), ('admin', 'Admin')], default='technician', max_length=20),
        ),
    ]
