# Generated by Django 6.1.1 on 2026-09-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="If set, this account only sees this customer's fleet (a client portal login). Leave blank for the consulting business's own staff, who see every customer's fleet.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='tracker.customer'),
        ),
    ]
